### ISSUE TITLE
Unable to Access External Media.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [meonwax/soundboard#1]
Title says all.  SD Card 1 is where I keep all.

**Comment by meonwax** [comment]
Hi,

thank you for your bug report.
To be able to take a look into your issue, i need a few more details:
- Please provide the exact OS version as well as the version of the Soundboard app you are using
- Do you get any error message?
- Are the contents of the file picker empty?

If you are on Marshmallow, try to install the latest [release 0.9.2](https://github.com/meonwax/soundboard/releases).
I fixed some issues concerning the runtime permissions introduced in Android Marshmallow

Regards

**Comment by meonwax** [comment]
Ok, even though i didn't get any further details from you, i think i see a potential issue here:
Currently, you can't select any other media directory but the internal SD card.
It should be possible to select the internal **or** external SD card and maybe even and attached USB storage to import sound files from.

I classify this as an enhancemnet since the current implementation for its own works fine, i think.

**Comment by locutis-of-borg-1999** [comment]
I've been a nit busy...

Android 4.1.2 "Jelly Bran".
Soundboard 0.9.2.
No errors.
Displays internal storage "SDcard0", just fine.  

Prior to upgrade to current version, it found some media files, automatically.  I added them, but now they are gone from the app'.

It's a great little app', but many people keep their sound files, and all non system data, on their inserted SD/TF cards.

**Comment by meonwax** [comment]
> Prior to upgrade to current version, it found some media files, automatically. I added them, but now they are gone from the app'.

Sorry for that. This is due to the change of the storage location for imported sounds. See the changelog [here](https://github.com/meonwax/soundboard/releases/tag/0.9.2).

> It's a great little app', but many people keep their sound files, and all non system data, on their inserted SD/TF cards.

Thanks. I will add a storage location selection as described above.

**Comment by locutis-of-borg-1999** [comment]
:-)

**Comment by meonwax** [comment]
I just committed an implementation.
Please try if it works for you and let me know.
You can either build it by yourself or grab a snapshot build [here](https://meonwax.de/soundboard/snapshots/files/soundboard-snapshot-1c9f405.apk).

**Comment by meonwax** [comment]
I think this works - at least for me as i also have an external sd card.
So i close this issue now.
