### ISSUE TITLE
Unable to import whole directory with soundfiles

### ISSUE THREAD

**Issue by ghost** [meonwax/soundboard#2]
I have plenty of files I want to import into soundboard.
I want to import a whole folder instead of choosing every file one by one.
Please make it possible. Thanks a lot!

**Comment by meonwax** [comment]
Hi,

thanks for your feature request.
This seems to be a desirable feature.
I will think about an implementation and let you know.

regards

**Comment by meonwax** [comment]
I just committed an implementation of this suggestion.
Please try and tell me what you think.

**Comment by ghost** [comment]
Sorry, I am a noob and don't even know how to compile it so I need an APK file.

Also I have another feature request: when I have imported many files I have to scroll up/down to find the sample I want to use. Maybe the buttons can be made smaller or be aligned in 2 or 3 columns so more samples can be displayed at once?

**Comment by meonwax** [comment]
> Sorry, I am a noob and don't even know how to compile it so I need an APK file.

Try this [snapshot build](https://transfer.sh/ENKeJ/soundboard-snapshot-160224.apk). Please install and report.

> Also I have another feature request: when I have imported many files I have to scroll up/down to find the sample I want to use. Maybe the buttons can be made smaller or be aligned in 2 or 3 columns so more samples can be displayed at once?

I plan to add a 'grid'-view you can switch to when the entry list is too long. I will create a new feature request for this.

**Comment by ghost** [comment]
APK does'nt open. "Error parsing the package"

**Comment by meonwax** [comment]
Your download seems to be corrupt. The uploaded APK is definitely working.
Please verify that the MD5 sum is `10345f5b0374b3ed514dccccd45363a5`.

**Comment by ghost** [comment]
MD5 sum is exactly like written by you. Downloaded again at home from PC. Not working. Same error.

**Comment by meonwax** [comment]
You are totally right! My fault. _Definitely_ is not that **definitely** :D

I completly messed up the apk signing process. It seems that all my last releases here on Github weren't correctly signed. I will fix this asap, but for now you can go with a quick built [debug version](https://transfer.sh/iac7W/soundboard-debug-160224.apk). MD5 is `8546404e5485cb4a7af45dab7c25c6d8`.

Please test this and report, so i can close this issue (hopefully).

**Comment by ghost** [comment]
Working :-) THANKS!
But: Files are mixed, there seems to be no specific order. Would be cool if they would be sorted in alphabetic order.

**Comment by meonwax** [comment]
This is fine.
Sorting entries is another feature on my list. I will also create a new issue for that.
