### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page, 0.9.2.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [meonwax/soundboard#3]
A great app', but all on F-Droid should include a Changelog Link, on the Info' Page, within the F-Droid app'.  Current, 0.9.2.

**Comment by meonwax** [comment]
Thanks for the suggestion.

I could add the [Changelog](https://f-droid.org/manual/html_node/Changelog.html#Changelog) meta tag in F-Droid to link to the Github releases page.
This is the place where i list important changes and updates.

**Comment by meonwax** [comment]
I created a [merge request](https://gitlab.com/fdroid/fdroiddata/merge_requests/1227) on F-Droid's Gitlab repo to add a changelog link to the Github releases page.
Once it is merged, it should soon be available on the F-Droid clients and website.

**Comment by locutis-of-borg-1999** [comment]
:-)
