### ISSUE TITLE
Overview for huge sound lists (tagcloud, ...)

### ISSUE THREAD

**Issue by Matthias84** [meonwax/soundboard#5]
I noticed, that it's getting hard to find an particular jingle / sound as the order is only based on the time when the files got added and you must scroll slow enough to read the names:
![screenshot_2016-03-13-11-27-30](https://cloud.githubusercontent.com/assets/217511/13728167/840e57a4-e90f-11e5-932e-71689f3cecbc.png)

So I like to suggest to introduce an tagcloud based view ([example](http://i.stack.imgur.com/pRRvj.png)), so the user can quickly filter the list and reduce it to a small amount of samples. So if you add a file, it asks you to assign (existing|new) tags. At the start screen you can then pick one of the tags and get all of the files which belong to this category.

Bonus: Ship the app with some usful tags (TV, politics, nerd, ...)

**Comment by meonwax** [comment]
I think this would add an enormous amount of complexity here.
Maybe your issue would be solved if #4 grid view and/or #7 list sorting will be integrated?

**Comment by Matthias84** [comment]
Indeed both ideas would help to deal with the catalogue, but they don't split it up. So you still have to browse all the list to find what you are looking for, while if you could use categories, you get an speedup

**Comment by meonwax** [comment]
I don't have much time to spend on this project, so i have to wisely select the features to implement.
I think grid view and sorting are features people would most benefit of.

However, a category view would be nice, but it has to integrate nice into the UI.

Are you interested of contributing some code?

**Comment by Matthias84** [comment]
@meonwax Sorry but I'm not an Android coder, but I know the problem of a lack of time ;)

**Comment by meonwax** [comment]
Ok, so i close this issue now.
I also have a few other projects that need do be done first, but i plan to extend this little app further and further in the future.
As long as you follow the releases on F-Droid you won't miss anything.
